### PR TITLE
Web3 guides color fix and formatting

### LINKED ISSUE #6: Web3 Guides color fix and Formatting of code
There is an issue with Web3 Guides dropbar and text color while switching between dark and light mode and I've fixed it and also formatted the code.
Please assign me this issue. I've already fixed it and want to send a PR.

### PR DESCRIPTION
**Pull request by VedantAnand17**
closes #6 

In this PR, I changed the color issue of web3 Guides option in the Navbar and did some code formatting and dependencies upgradation.

### CODE REVIEW

**Comment by VedantAnand17** [comment]
Kindly check the PR, it has no conflicts with the base branch

**Review by Paramchoudhary — APPROVED** [review]
merged, thank you vedant for your contribution

**Comment by Paramchoudhary** [comment]
Thank you, Vidant, for your contribution.

**Comment by VedantAnand17** [comment]
You're welcome :)

**Pull request merged**
